### ISSUE TITLE
Mobile Menu Overlaps Footer on iOS Safari (Viewport Height Calculation Error)

### ISSUE THREAD

**Issue by SilentCoder-HI** [dubinc/dub#2231]
## **Environment:**  
- **Device:** iPhone 12/13/14 (Tested on iOS 16/17)  
- **Browser:** Safari  
- **Reproducible:** Always  

## **Current Behavior:**  
When opening the mobile menu and scrolling down, the menu (with `position: fixed`) overlaps the footer, blocking clickable elements.

## **Steps to Reproduce:**  
1. Open [[Dub.co](https://dub.co/)](https://dub.co) on iOS Safari.  
2. Tap the "hamburger" menu icon.  
3. Scroll down → Menu covers footer links (e.g., "Privacy Policy").  

## **Expected Behavior:**  
The mobile menu should scroll above the footer without overlap.

## **Root Cause:**  
- Safari’s incorrect `100vh` calculation (includes browser UI, causing `position: fixed` to extend beyond visible viewport).
- Missing viewport height adjustment for the footer.

## **Suggested Fix:**  
Replace `height: 100vh` with dynamic CSS:

```css
/* Fix for iOS Safari viewport bug */
@media (max-width: 640px) {
  .mobile-menu {
    position: fixed;
    height: calc(100dvh - 60px); /* 60px = footer height */
    bottom: 0;
    overflow-y: auto;
  }
}
```

### **Key Changes:**  
✅ Uses `100dvh` (dynamic viewport height) instead of `100vh`.  
✅ Subtracts footer height to prevent overlap.  

## **Impact:**  
- Fixes navigation for ~20% of mobile traffic (iOS Safari users).  
- Aligns with Safari’s viewport behavior.  

## **Labels:**  
`bug`, `ios`, `mobile`, `ui`, `accessibility`
